move to all lowercase variables; improved -help checker; other small modifications

diff --git a/onyourfeat/fsfinfo b/onyourfeat/fsfinfo
--- a/onyourfeat/fsfinfo
+++ b/onyourfeat/fsfinfo
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Author: Luka Ruzic
 
-EXIT_multiple_parameters=3
+exit_multiple_parameters=3
 
 usage() {
     echo "
@@ -9,11 +9,12 @@ Usage:  fsfinfo <option> <analysis.(g)feat | design.fsf>
 Description:
   retrieve information and properties of FEAT designs
   many of the higher level options will scan through all lower levels or input analyses
-  inconsistencies among lower levels or input analyses are reported with a warning and exit status $EXIT_multiple_parameters
+  inconsistencies among lower levels or input analyses are reported with a warning and exit status $exit_multiple_parameters
 
-Modifying Options:
-    --c    when scanning inputs/lower levels, print warning if there are differing parameters being used and
-           exit with status $EXIT_multiple_parameters
+  When scanning inputs/lower levels, it is assumed that all input analyses should
+    use the same parameters. If they do not, fsfinfo will print a warning and
+    exit with status $exit_multiple_parameters
+
 Options:
          -i             input (directories, copes, or functional data)
          -1i            just first input (directory, cope, or functional image)
@@ -39,9 +40,11 @@ Options:
          -s             subjects used (assumes input analyses live in subject directories)
          -n             number of inputs
          -i             direct input directories (identical to -l in any two level analysis)
-         -1i            just first direct input directory (identical to -l in any two level analysis)
          -l             lower level FEAT directories
+         -1i            just first direct input directory (identical to -l in any two level analysis)
          -1l            just first lower level FEAT directory
+         -im            view model for just first input analysis
+         -lm            view model for just first lower level analysis
          -icon          contrast names of input analyses (can be a lower level or an intermediate level) (real)
          -lcon          contrast names of lower level analyses (real)
          -icono         contrasts of input analyses (can be a lower level or an intermediate level) (orig)
@@ -66,7 +69,7 @@ if [ $# -ne 2 ]; then echo "ERROR: insufficient arguments" >&2; usage; fi
 schmecho() {
     if [ $# -gt 1 ]; then
 	echo "WARNING: different parameters in different lower levels" >&2
-	EXIT_STATUS=$EXIT_multiple_parameters
+	exit_status=$exit_multiple_parameters
     fi
 
     echo $* | tr ' ' '\n'
@@ -76,24 +79,24 @@ schmecho() {
 
 ### PARSE ARGUMENTS
 # first argument is the option
-OPT=$1
+opt=$1
 # second argument is (g)feat directory or fsf
 if [[ "$2" =~ \.g{0,1}feat/{0,1}$ ]]; then
-    FSF=$2/design.fsf
+    fsf=$2/design.fsf
 elif [[ "$2" =~ \.fsf$ ]]; then    
-    FSF=$2
+    fsf=$2
 else
     echo "ERROR: second argument ($2) is not a FEAT analysis directory or .fsf file" >&2
     usage
 fi
 
-if [ ! -f $FSF ]; then
-    echo "ERROR: no such design file as $FSF" >&2
+if [ ! -f $fsf ]; then
+    echo "ERROR: no such design file as $fsf" >&2
     exit 1
 fi
 
 # get type (1=lower, 2=higher)
-type=$(awk '$2 ~ /fmri\(level\)/ {print $3}' $FSF)
+type=$(awk '$2 ~ /fmri\(level\)/ {print $3}' $fsf)
 
 # check for higher level options applied to lower level analyses
 if [ $type -eq 1 ] && \
@@ -111,24 +114,24 @@ if [ $type -eq 1 ] && \
        -1lcono \
        -iev \
        -lev \
-       -lversion " =~ " "$OPT" " ]]; then
-    printf "INVALID OPTION:\n  $OPT is only for higher levels\n  $FSF is a lower level" >&2
+       -lversion " =~ " "$opt" " ]]; then
+    printf "INVALID OPTION:\n  $opt is only for higher levels\n  $fsf is a lower level" >&2
     exit 1
 fi
 
 # execute option
-case $OPT in
+case $opt in
     "-i")
-	awk '$2 ~ /feat_files\(/ {gsub("\"","",$3); print $3}' $FSF;;
+	awk '$2 ~ /feat_files\(/ {gsub("\"","",$3); print $3}' $fsf;;
 
     "-1i")
-	fsfinfo -i $FSF | head -1;;
+	awk '$2 ~ /feat_files\(/ {gsub("\"","",$3); print $3; exit}' $fsf;;
 
     "-t")
 	echo $type;;
     
     "-level")
-	x=$FSF
+	x=$fsf
 	while :; do
 	    let nlevels++
 	    x=$(fsfinfo -1i $x)
@@ -137,14 +140,14 @@ case $OPT in
 	echo $nlevels;;
     
     "-o")
-	awk '$2 ~ /fmri\(outputdir\)/ {gsub ("\"","",$3); print $3}' $FSF;;
-    
+	awk '$2 ~ /fmri\(outputdir\)/ {gsub ("\"","",$3); print $3}' $fsf;;
+
     "-im")
-	fsfinfo -m $(fsfinfo -1i $FSF);;
-
+	fsfinfo -m $(fsfinfo -1i $fsf);;
+    
     "-lm")
-	fsfinfo -m $(fsfinfo -1l $FSF);;
-
+	fsfinfo -m $(fsfinfo -1l $fsf);;
+    
     "-m")
 	if [ $type -eq 1 ]; then
 	    # print EVs (also find EV titles to print header for contrasts)
@@ -154,20 +157,20 @@ case $OPT in
 		let enum++
 		echo "$n $ev"
 
-		convolve=$(awk '$2 ~ /\(convolve'${n/EV/}'\)/ {print $3}' $FSF)		
-		evtitle=$(grep "(evtitle${n/EV/})" $FSF | cut -d\" -f2)
+		convolve=$(awk '$2 ~ /\(convolve'${n/EV/}'\)/ {print $3}' $fsf)		
+		evtitle=$(grep "(evtitle${n/EV/})" $fsf | cut -d\" -f2)
 		if [ $convolve -le 3 ]; then
 		    evtitles+=($evtitle)
 		    # catch temporal derivatives
-		    if [ $(awk '$2 ~ /\(deriv_yn'${n/EV/}'\)/ {print $3}' $FSF) -eq 1 ]; then
+		    if [ $(awk '$2 ~ /\(deriv_yn'${n/EV/}'\)/ {print $3}' $fsf) -eq 1 ]; then
 			let enum++
 			echo "${n} TEMPORAL DERIVATIVE"
 			evtitles+=(${evtitle}_deriv)
 		    fi
 		else 
 		    # catch basis functions
-		    nbasisfuncs=$(awk '$2 ~ /\(basisfnum'${n/EV/}'\)/ {print $3}' $FSF)
-		    if [ $(awk '$2 ~ /\(convolve'${n/EV/}'\)/ {print $3}' $FSF) -gt 3 ] && [ $nbasisfuncs -gt 0 ]; then
+		    nbasisfuncs=$(awk '$2 ~ /\(basisfnum'${n/EV/}'\)/ {print $3}' $fsf)
+		    if [ $(awk '$2 ~ /\(convolve'${n/EV/}'\)/ {print $3}' $fsf) -gt 3 ] && [ $nbasisfuncs -gt 0 ]; then
 			let enum+=$nbasisfuncs
 			for ((i=1;i<=nbasisfuncs;i++)); do 
 			    evtitles+=(${evtitle}_bf$i)
@@ -175,7 +178,7 @@ case $OPT in
 			echo BASIS FUNCTIONS: $nbasisfuncs
 		    fi
 		fi
-	    done < <(fsfinfo -evfiles $FSF)
+	    done < <(fsfinfo -evfiles $fsf)
 	    
 	    echo; echo CONTRASTS:
 	    # print header (EV titles found above spaced neatly in two rows (allows 18 characters before overlap/push))
@@ -195,56 +198,56 @@ case $OPT in
 		printf "%18s" ${evtitles[i]}
 	    done
 	    echo
-	    cnum=$(awk '$2 ~ /ncon_real/ {print $3}' $FSF)
+	    cnum=$(awk '$2 ~ /ncon_real/ {print $3}' $fsf)
 	    # print contrast coding matrix
 	    for ((c=1;c<=cnum;c++)); do
 		printf "%s   %s\n" \
-		    "$(for ((e=1;e<=enum;e++)); do awk '$2 ~ /fmri\(con_real'${c}.${e}'\)/ {print $3}' $FSF; done | awk '{printf (" %8s",$1)}')" \
-		    "$(fsfinfo -con $FSF | awk '$2=='$c'' | cut -d' ' -f3-)"
+		    "$(for ((e=1;e<=enum;e++)); do awk '$2 ~ /fmri\(con_real'${c}.${e}'\)/ {print $3}' $fsf; done | awk '{printf (" %8s",$1)}')" \
+		    "$(fsfinfo -con $fsf | awk '$2=='$c'' | cut -d' ' -f3-)"
 	    done
 	else
 	    echo EVs:
 	    echo -n "group"
-	    printf " %8s" $(grep evtitle $FSF | cut -d\" -f2 | tr '\n' ' ')
+	    printf " %8s" $(grep evtitle $fsf | cut -d\" -f2 | tr '\n' ' ')
 	    echo "   Input:"
-	    for ((i=1;i<=$(fsfinfo -n $FSF);i++)); do
-		a=$(awk '/set feat_files\('${i}'\)/ {gsub("\"","",$3); print $3}' $FSF)
-		n=$(awk '$2 ~ /fmri\(evg'${i}'\./ {print $3}' $FSF)
+	    for ((i=1;i<=$(fsfinfo -n $fsf);i++)); do
+		a=$(awk '/set feat_files\('${i}'\)/ {gsub("\"","",$3); print $3}' $fsf)
+		n=$(awk '$2 ~ /fmri\(evg'${i}'\./ {print $3}' $fsf)
 		printf "%4d %s   %s\n" \
-		    "$(awk '$2 ~ /fmri\(groupmem\.'${i}'\)/ {print $3}' $FSF)" \
-		    "$(awk '$2 ~ /fmri\(evg'${i}'\./ {print $3}' $FSF | awk '{printf (" %8s",$1)}')" \
+		    "$(awk '$2 ~ /fmri\(groupmem\.'${i}'\)/ {print $3}' $fsf)" \
+		    "$(awk '$2 ~ /fmri\(evg'${i}'\./ {print $3}' $fsf | awk '{printf (" %8s",$1)}')" \
 		    $a
 	    done
 	    echo; echo CONTRASTS:
 	    
-	    printf "%5s" ""; printf " %8s" $(grep evtitle $FSF | cut -d\" -f2); echo
-	    [ $(awk '$2 ~ /con_mode\)/ {print $3}' $FSF) == "orig" ] && ctype=orig || ctype=real
-	    cnum=$(awk '$2 ~ /ncon_'${ctype}'\)/ {print $3}' $FSF)	
-	    enum=$(fsfinfo -ev $FSF | wc -l)
+	    printf "%5s" ""; printf " %8s" $(grep evtitle $fsf | cut -d\" -f2); echo
+	    [ $(awk '$2 ~ /con_mode\)/ {print $3}' $fsf) == "orig" ] && ctype=orig || ctype=real
+	    cnum=$(awk '$2 ~ /ncon_'${ctype}'\)/ {print $3}' $fsf)	
+	    enum=$(fsfinfo -ev $fsf | wc -l)
 	    for ((c=1;c<=cnum;c++)); do
 		printf "%4s %s   %s\n" \
 		    "" \
-		    "$(for ((e=1;e<=enum;e++)); do awk '$2 ~ /'con_${ctype}${c}.${e}\)'/ {print $3}' $FSF; done | awk '{printf (" %8s",$1)}')" \
-		    "$(fsfinfo -con $FSF | awk '$2=='$c'' | cut -d' ' -f3-)"
+		    "$(for ((e=1;e<=enum;e++)); do awk '$2 ~ /'con_${ctype}${c}.${e}\)'/ {print $3}' $fsf; done | awk '{printf (" %8s",$1)}')" \
+		    "$(fsfinfo -con $fsf | awk '$2=='$c'' | cut -d' ' -f3-)"
 	    done
 	fi;;
 
     "-con" | "-hcon")
-	sed -n 's|.*fmri(conname_real\.\(.*\)) \"\(.*\)\"|contrast \1 \2|p' $FSF;;
+	sed -n 's|.*fmri(conname_real\.\(.*\)) \"\(.*\)\"|contrast \1 \2|p' $fsf;;
 
     "-cono" | "-hcono")
-	sed -n 's|.*fmri(conname_orig\.\(.*\)) \"\(.*\)\"|contrast \1 \2|p' $FSF;;
+	sed -n 's|.*fmri(conname_orig\.\(.*\)) \"\(.*\)\"|contrast \1 \2|p' $fsf;;
 
     "-ev")
-	for ((e=1;e<=$(awk '$2 ~ /fmri\(evs_orig\)/ {print $3}' $FSF);e++)); do
-	    sed -n 's|.*fmri(evtitle'${e}') \"\(.*\)\"|EV'${e}' \1|p' $FSF
+	for ((e=1;e<=$(awk '$2 ~ /fmri\(evs_orig\)/ {print $3}' $fsf);e++)); do
+	    sed -n 's|.*fmri(evtitle'${e}') \"\(.*\)\"|EV'${e}' \1|p' $fsf
 	done;;
 
     "-evfiles")
 	if [ $type -eq 1 ]; then
-	    sed -n 's|.*fmri(custom\(.*\)) \"\(.*\)\"|EV\1 \2|p' $FSF
+	    sed -n 's|.*fmri(custom\(.*\)) \"\(.*\)\"|EV\1 \2|p' $fsf
 	else
-	    for i in $(fsfinfo -l $FSF); do
+	    for i in $(fsfinfo -l $fsf); do
 		if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i"; exit 77; fi
 		fsfinfo -evfiles $i/design.fsf
 	    done
@@ -252,9 +255,9 @@ case $OPT in
     
     "-tr")
 	if [ $type -eq 1 ]; then
-	    awk '$2 ~ /fmri\(tr\)/ {print $3}' $FSF
+	    awk '$2 ~ /fmri\(tr\)/ {print $3}' $fsf
 	else
-	    p=$(for i in $(fsfinfo -l $FSF); do
+	    p=$(for i in $(fsfinfo -l $fsf); do
 		if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i"; exit 77; fi
 		fsfinfo -tr $i/design.fsf
 	    done | sort -n | uniq)
@@ -263,9 +266,9 @@ case $OPT in
 
     "-vols")
 	if [ $type -eq 1 ]; then
-	    awk '$2 ~ /fmri\(npts\)/ {print $3}' $FSF
+	    awk '$2 ~ /fmri\(npts\)/ {print $3}' $fsf
 	else
-	    p=$(for i in $(fsfinfo -l $FSF); do
+	    p=$(for i in $(fsfinfo -l $fsf); do
 		if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i"; exit 77; fi
 		fsfinfo -vols $i/design.fsf
 	    done | sort -n | uniq)
@@ -273,7 +276,7 @@ case $OPT in
 	fi;;
 
     "-mod")
-	awk -v x=$(awk '$2 ~ /fmri\(mixed_yn\)/ {print $3}' $FSF) '/# Higher-level modelling/ {go=1; next} /set fmri\(mixed_yn\)/ {exit} go==1 && $2==x {print substr($0,7)}' $FSF;;
+	awk -v x=$(awk '$2 ~ /fmri\(mixed_yn\)/ {print $3}' $fsf) '/# Higher-level modelling/ {go=1; next} /set fmri\(mixed_yn\)/ {exit} go==1 && $2==x {print substr($0,7)}' $fsf;;
 
     "-dof")
 	if [ $type -eq 1 ]; then
@@ -284,25 +287,25 @@ case $OPT in
                  $2 ~ /fmri\(reginitial_highres_dof\)/ && ihr {print $0} \
                  $2 ~ /fmri\(reghighres_dof\)/ && hr {print $0} \
                  $2 ~ /fmri\(regstandard_dof\)/ && std {print $0}' \
-		$FSF | sed 's|.*fmri(\(.*_dof\))[ ]*\(.*\)|\1:\2|' | sort -n | uniq
+		$fsf | sed 's|.*fmri(\(.*_dof\))[ ]*\(.*\)|\1:\2|' | sort -n | uniq
 	else
-	    p=$(for i in $(fsfinfo -l $FSF); do
+	    p=$(for i in $(fsfinfo -l $fsf); do
 		if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i" >&2; exit 1; fi
 		fsfinfo -dof $i
 	    done | sort -n | uniq)
 
 	    if [ $(echo $p | tr ' ' '\n' | cut -d: -f1 | sort -n | uniq -c | awk '$1>1 {s++; exit} END {print s*1}') -gt 0 ]; then
 		echo "WARNING: different parameters in different lower levels" >&2
-		EXIT_STATUS=$EXIT_muliple_parameters
+		exit_status=$exit_muliple_parameters
 	    fi
 	    echo $p | tr ' ' '\n' | sed 's| *$||' | sort -n | uniq
 	fi;;
     
     "-hpf")
 	if [ $type -eq 1 ]; then
-	    awk '$2 ~ /fmri\(paradigm_hp\)/ {print $3}' $FSF
+	    awk '$2 ~ /fmri\(paradigm_hp\)/ {print $3}' $fsf
 	else
-	    p=$(for i in $(fsfinfo -l $FSF); do
+	    p=$(for i in $(fsfinfo -l $fsf); do
 		if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i" >&2; exit 77; fi
 		fsfinfo -hpf $i
 	    done | sort -n | uniq)
@@ -311,9 +314,9 @@ case $OPT in
 
     "-mc")
 	if [ $type -eq 1 ]; then
-	    awk '$2 ~ /fmri\(mc\)/ {if ($3) print 1; else print 0}' $FSF
+	    awk '$2 ~ /fmri\(mc\)/ {if ($3) print 1; else print 0}' $fsf
 	else
-	    p=$(for i in $(fsfinfo -l $FSF); do 
+	    p=$(for i in $(fsfinfo -l $fsf); do 
 		if [ ! -d $i ]; then 
 		    echo "ERROR: input analysis does not exist: $i" >&2; exit 77
 		fi
@@ -324,7 +327,7 @@ case $OPT in
 
     "-stc")
 	if [ $type -eq 1 ]; then
-	    case $(awk '$2 ~ /fmri\(st\)/ {print $3}' $FSF) in
+	    case $(awk '$2 ~ /fmri\(st\)/ {print $3}' $fsf) in
 		"0") echo none;;
 		"1") echo regular_up;;
 		"2") echo regular_down;;
@@ -333,7 +336,7 @@ case $OPT in
 		"5") echo interleaved;;
 	    esac
 	else
-	    p=$(for i in $(fsfinfo -l $FSF); do
+	    p=$(for i in $(fsfinfo -l $fsf); do
 		if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i" >&2; exit 77; fi
 		fsfinfo -stc $i
 	    done | sort -n | uniq)
@@ -342,9 +345,9 @@ case $OPT in
 
     "-smooth")
 	if [ $type -eq 1 ]; then
-	    awk '$2 ~ /fmri\(smooth\)/ {print $3"mm"}' $FSF
+	    awk '$2 ~ /fmri\(smooth\)/ {print $3"mm"}' $fsf
 	else
-	    p=$(for i in $(fsfinfo -l $FSF); do
+	    p=$(for i in $(fsfinfo -l $fsf); do
 		if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i" >&2; exit 77; fi
 		fsfinfo -smooth $i
 	    done | sort | uniq)
@@ -352,124 +355,125 @@ case $OPT in
 	fi;;
 
     "-version")
-	awk '$2 ~ /fmri\(version\)/ {print $3}'  $FSF;;
+	awk '$2 ~ /fmri\(version\)/ {print $3}'  $fsf;;
 
 # HIGHER LEVELS ONLY OPTIONS
     "-a")
-	awk '/set feat_files/ {print $3}' $FSF | cut -d\" -f2 | sed 's|.*/||' | sort -n | uniq;;
+	awk '/set feat_files/ {print $3}' $fsf | cut -d\" -f2 | sed 's|.*/||' | sort -n | uniq;;
 
     "-s")
-	for i in $(fsfinfo -l $FSF); do
+	for i in $(fsfinfo -l $fsf); do
 	    basename $(dirname $i)
 	done | sort -n | uniq;;
 
     "-n")
-	awk '$2 ~ /fmri\(npts\)/ {print $3}' $FSF;;
+	awk '$2 ~ /fmri\(npts\)/ {print $3}' $fsf;;
 
     "-l")
 	findlowers() {
-	    for a in $*; do
-#		if [ $(awk '/set fmri\(level\)/ {print $3}' $a/design.fsf) -eq 2 ]; then     # this is faster, but would miss any improvements to fsfinfo -t
-# using getlowers is even faster, but that assumes no more than three levels in any analysis... safe assumption?
-		if [ "$(fsfinfo -t $a)" -eq 2 ]; then
-		    findlowers $(fsfinfo -i $a)
-		else
-		    echo $a
-		fi
-	    done
+	    if [ $(fsfinfo -t $1) -eq 2 ]; then
+		for i in $(fsfinfo -i $1); do 
+		    findlowers $i
+		done
+	    else
+		echo $1
+	    fi
 	}
-
-	findlowers $FSF;;
+	findlowers $fsf;;
 
     "-1l")
-	fsfinfo -l $FSF | head -1;;
+	x=$fsf
+	while [ $(fsfinfo -t $x) -eq 2 ]; do
+	    x=$(fsfinfo -1i $x)
+	done
+	echo $x;;
 
     "-icon")
-	p=$(for i in $(fsfinfo -i $FSF); do
+	p=$(for i in $(fsfinfo -i $fsf); do
 	    if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i" >&2; exit 77; fi
 	    fsfinfo -con $i
 	done | sort -k2 -n | uniq)
 
 	if [ "$p" ] && [ $(echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g' | awk '{print $1,$2}' | sort -n | uniq -c | awk '{print $1}' | sort -n | tail -1) -gt 1 ]; then
 	    echo "WARNING: different parameters in different lower levels" >&2
-	    EXIT_STATUS=$EXIT_multiple_parameters
+	    exit_status=$exit_multiple_parameters
 	fi
 	echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g';;    
     
     "-1icon")
-	fsfinfo -con $(fsfinfo -1i $FSF);;
+	fsfinfo -con $(fsfinfo -1i $fsf);;
 	
     "-lcon")
-	p=$(for i in $(fsfinfo -l $FSF); do
+	p=$(for i in $(fsfinfo -l $fsf); do
 	    if [ ! -d $i ]; then echo "ERROR: lower level analysis does not exist: $i" >&2; exit 77; fi
 	    fsfinfo -con $i
 	done | sort -k2 -n | uniq)
 	
 	if [ "$p" ] && [ $(echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g' | awk '{print $1,$2}' | sort -n | uniq -c | awk '{print $1}' | sort -n | tail -1) -gt 1 ]; then
             echo "WARNING: different parameters in different lower levels" >&2
-            EXIT_STATUS=$EXIT_multiple_parameters
+            exit_status=$exit_multiple_parameters
         fi
 	echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g';;
 
     "-1lcon")
-	fsfinfo -con $(fsfinfo -1l $FSF);;
+	fsfinfo -con $(fsfinfo -1l $fsf);;
 
     "-icono")
-	p=$(for i in $(fsfinfo -i $FSF); do
+	p=$(for i in $(fsfinfo -i $fsf); do
 	    if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i" >&2; exit 77; fi
 	    fsfinfo -cono $i
 	done | sort -k2 -n | uniq)
 
 	if [ "$p" ] && [ $(echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g' | awk '{print $1,$2}' | sort -n | uniq -c | awk '{print $1}' | sort -n | tail -1) -gt 1 ]; then
             echo "WARNING: different parameters in different lower levels" >&2
-            EXIT_STATUS=$EXIT_multiple_parameters
+            exit_status=$exit_multiple_parameters
         fi
         echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g';;
 
     "-1icono")
-	fsfinfo -cono $(fsfinfo -1i $FSF);;
+	fsfinfo -cono $(fsfinfo -1i $fsf);;
 
     "-lcono")
-	p=$(for i in $(fsfinfo -l $FSF); do
+	p=$(for i in $(fsfinfo -l $fsf); do
             if [ ! -d $i ]; then echo "ERROR: lower level analysis does not exist: $i" >&2; exit 77; fi
             fsfinfo -cono $i
         done | sort -k2 -n | uniq)
 
 	if [ "$p" ] && [ $(echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g' | awk '{print $1,$2}' | sort -n | uniq -c | awk '{print $1}' | sort -n | tail -1) -gt 1 ]; then
             echo "WARNING: different parameters in different lower levels" >&2
-            EXIT_STATUS=$EXIT_multiple_parameters
+            exit_status=$exit_multiple_parameters
         fi
 	echo $p | sed 's| \(contrast [0-9]*\)|\n\1|g';;
 
     "-1lcono")
-	fsfinfo -cono $(fsfinfo -1l $FSF);;
+	fsfinfo -cono $(fsfinfo -1l $fsf);;
 
     "-iev")
-	p=$(for a in $(fsfinfo -i $FSF); do
+	p=$(for a in $(fsfinfo -i $fsf); do
 	    if [ ! -d $i ]; then echo "ERROR: input analysis does not exist: $i" >&2; exit 77; fi
 	    fsfinfo -ev $a
 	done | sort -k1 -n | uniq)
 	
 	if [ "$p" ] && [ $(echo $p | sed 's| \(EV[0-9]*\)|\n\1|g' | awk '{print $1}' | sort -n | uniq -c | awk '{print $1}' | sort -n | tail -1) -gt 1 ]; then
 	    echo "WARNING: different parameters in different lower levels" >&2
-	    EXIT_STATUS=$EXIT_multiple_parameters
+	    exit_status=$exit_multiple_parameters
 	fi
 	echo $p | sed 's| \(EV[0-9]*\)|\n\1|g';;
 
     "-lev")
-	p=$(for a in $(fsfinfo -l $FSF); do
+	p=$(for a in $(fsfinfo -l $fsf); do
 	    if [ ! -d $i ]; then echo "ERROR: lower level analysis does not exist: $i" >&2; exit 77; fi
 	    fsfinfo -ev $a
 	done | sort -k1 -n | uniq)
 
 	if [ "$p" ] && [ "$(echo $p | sed 's| \(EV[0-9]*\)|\n\1|g' | awk '{print $1}' | sort -n | uniq -c | awk '$1>1')" ]; then
 	    echo "WARNING: different parameters in different lower levels" >&2
-            EXIT_STATUS=$EXIT_multiple_parameters
+            exit_status=$exit_multiple_parameters
 	fi
 	echo $p | sed 's| \(EV[0-9]*\)|\n\1|g';;
 
     "-lversion")
-	p=$(for i in $(fsfinfo -l $FSF); do
+	p=$(for i in $(fsfinfo -l $fsf); do
 	    if [ ! -d $i ]; then echo "ERROR: lower level analysis does not exist: $i" >&2; exit 77; fi
 	    fsfinfo -version $i/design.fsf
 	done | sort -n | uniq)
@@ -477,8 +481,8 @@ case $OPT in
 	schmecho $p;;
 
     *)
-	echo "UNRECOGNIZED OPTION: $OPT"
+	echo "UNRECOGNIZED OPTION: $opt"
 	usage
 esac
 
-exit ${EXIT_STATUS:-0}
+exit ${exit_status:-0}
