separated threshold option; fixed thresholding bug; allow multiple atlas requests; improve reading in of coordinates (enforce position)

diff --git a/utils/mm2label b/utils/mm2label
--- a/utils/mm2label
+++ b/utils/mm2label
@@ -20,11 +20,14 @@ Description:  takes MNI coordinates (mm) <x> <y> <z> and returns a name, hemisph
 Options:
   -icbm
      use the ICBM Lancaster coordinate conversion (default: Brett coordinates) (only applies to TD, not -a atlases)
-  -a [thr%] <ATLAS CODE>
+  -a <ATLAS CODE>
      report from an FSL probabilistic atlas instead of the Talairach Daemon
-     threshold regions at thr% (DEFAULT: 0%)
+     threshold regions at thr% (DEFAULT: 0%)     
+     ex: mm2label 0 0 0 -a 6,7
+  -athr <pct>
+     Threshold probabilistic regions reported (by -a) at <pct>%
      (only integer percenteges allowed)
-     ex: mm2label 0 0 0 -a 75% 1
+     ex: mm2label 0 0 0 -a 6,7 -athr 25
 ATLAS CODES:"
     for (( i=1; i<${#atlas_decoder[*]} ; i++ )); do
 	echo "          $i: ${atlas_decoder[i]}"
@@ -49,38 +52,52 @@ too_many_tries() {
 tdquery() {
 #    java org.talairach.PointToTD 3:9,$1,$2,$3 2>&1 | tr '\n' %
     /usr/bin/java -cp /usr/local/talairach/talairach.jar org.talairach.PointToTD 3:9, $1, $2, $3 host=${4}:1600 | tr '\n' %
-    [ ${PIPESTATUS[0]} -ne 0 ] && echo "ERROR: TD call failed"
+    [ ${PIPESTATUS[0]} -ne 0 ] && echo "ERROR: TD call failed" 2>/dev/null
 }
 
 
 ### PARSE ARGUMENTS
-pct=0
+# read in coordinates (must be first three arguments)
 n=0
+while [ "$1" ]&&[[ "$1" =~ ^[0-9]*$ ]]; do
+    coordinates+="$1 "
+    let n++
+    shift
+done
+if [ $n -ne 3 ]; then
+    echo "ERROR: 3 and only 3 coordinates allowable" >&2
+    exit 1
+fi
+
+# options
+athr=0
 while [ "$1" ]; do
-    if [[ "$1" =~ ^-{0,1}[0-9]*$ ]]; then
-	coordinates+="$1 "
-	let n++
-	shift
-    elif [ "$1" == "-icbm" ]; then
+    if [ "$1" == "-icbm" ]; then
 	icbm=set
-	shift
     elif [ "$1" == "-vox" ]; then
 	vox=set
-	shift
     elif [ "$1" == "-a" ]; then
-	if [ ${2:${#2}-1:1} == "%" ]; then pct=${2%\%}; shift; fi
-	atlas=("${atlas_decoder[$2]}")
-	if [ ! "$atlas" ]; then echo "ERROR: $2 is not a valid atlas code" >&2; exit 1; fi
-	shift 2
+	while [ $2 ]&&[ ${2:0:1} != "-" ]; do
+	    if [ $2 -lt 0 ]||[ $2 -gt ${#atlas_decoder[*]} ]; then
+		echo "ERROR: $2 is not a valid atlas code" >&2
+		exit 1
+	    fi
+	    
+	    atlas+=("${atlas_decoder[$2]}")
+	    shift
+	done
+    elif [ "$1" == "-athr" ]; then
+	shift; athr=$1
+    elif [ "$1" == "-v" ]; then
+	verbose=set
     else 
 	echo "UNRECOGNIZED ARGUMENT: $1" >&2
+	usage
     fi
+    shift
 done
 
 ### error checking
-if [ $n -ne 3 ]; then
-    let e++; echo "ERROR: 3 and only 3 coordinates allowable" >&2
-fi
 if [[ "$p" =~ [^0-9] ]]; then
     let e++; echo "ERROR: only integers acceptable" >&2
 fi
@@ -114,35 +131,20 @@ if [ ! "$atlas" ]; then
     region="$(echo $fields | cut -d\; -f2 | tr ' ' _)"
     BArea="$(echo $fields | cut -d\; -f3 | cut -d" " -f3)"    
 
-#    if [[ "$tdoutput" =~ Brodmann\ area ]];then # there's a BA
-#	fields="$(echo $tdoutput | awk -F',' 'BEGIN {RS="%"} /Brodmann/ {print $1";" $3";" $5; exit}')"
-#
-#	hemisphere="$(echo $fields | cut -d\; -f1 | grep -Eo '^[LR]')"
-#	region="$(echo $fields | cut -d\; -f2 | tr ' ' _)"
-#	BArea="$(echo $fields | cut -d\; -f3 | cut -d" " -f3)"    
-#    elif [[ "$tdoutput" =~ Cerebellum ]]; then # it's cerebellum
-#	fields="$(echo $tdoutput | awk -F',' 'BEGIN {RS="%"} /Brodmann/ {print $1";" $3";" $5; exit}')"
-#
-#	hemisphere="$(echo $tdoutput | cut -d\; -f1 | grep -Eo '^[LR]')"
-#	region="$()"
-#	BArea="N/A"
-#    elif [ ??? ]; then  # it's subcortical
-#    else  # it's white matter	
-#    fi
-
-
-
     # return output
     [ $region ] && echo "$region $([ $hemisphere ] && echo $hemisphere) $([ $BArea ] && echo BA$BArea)" || exit 9
 else
-    while read pct region; do 
-	if [[ "$pct" =~ [^0-9] ]]; then
-	    label+=" $pct $region;"
-	else
-	    [ $pct -ge $pct ] && label+=" ${pct}% ${region};"
-	fi
-    done < <(atlasquery -a "$atlas" -c ${coordinates// /,} | sed -e 's|.*<br>||' -e 's|, \([0-9]*%\)|\n\1|g' -e 's|,|:|g' -e 's|%||g')
-    echo $label | sed -e 's|^ ||' -e 's|;$||'
+    for ((i=0; i<${#atlas[*]}; i++)); do
+	label=""
+	while read pct region; do 
+	    if [[ "$pct" =~ [^0-9] ]]; then
+		label+=" $pct $region;"
+	    else
+		[ $pct -ge $athr ] && label+=" ${pct}% ${region};"
+	    fi
+	done < <(atlasquery -a "${atlas[i]}" -c ${coordinates// /,} | sed -e 's|.*<br>||' -e 's|, \([0-9]*%\)|\n\1|g' -e 's|,|:|g' -e 's|%||g')
+	echo $label | sed -e 's|^ ||' -e 's|;$||'
+    done
 fi
 
 
